---
default: &default
  cloud_name: <%= Rails.application.secrets.cloud_name %>
  api_key: <%= Rails.application.secrets.cloud_api_key %>
  api_secret: <%= Rails.application.secrets.cloud_api_secret %>

development:
  <<: *default
  enhance_image_tag: true
  static_image_support: false

production:
  <<: *default
  enhance_image_tag: true
  static_image_support: true

test:
  <<: *default
  enhance_image_tag: true
  static_image_support: false
